language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
install:
- pip install ghp-import
- git clone https://github.com/getpelican/pelican-plugins
script:
- make publish github